# Generated by Django 5.1.7 on 2025-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthighlights',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
