# Generated by Django 5.1.7 on 2025-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_abouthighlights_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-banner/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('apply_now_url', models.URLField(blank=True, null=True)),
                ('contact_us_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
