# Generated by Django 5.1.7 on 2025-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_mission_vision/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='apply_now_url',
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='contact_us_url',
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='description',
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_banner/'),
        ),
    ]
