# Generated by Django 5.1.7 on 2025-04-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutcoursesoffered_aboutcoursesofferedtitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmissionvision',
            old_name='description',
            new_name='mission_description',
        ),
        migrations.RenameField(
            model_name='aboutmissionvision',
            old_name='image',
            new_name='mission_image',
        ),
        migrations.RenameField(
            model_name='aboutmissionvision',
            old_name='title',
            new_name='mission_title',
        ),
        migrations.AddField(
            model_name='aboutmissionvision',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='about_mission_vision/'),
        ),
        migrations.AddField(
            model_name='aboutmissionvision',
            name='video_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_mission_vision/'),
        ),
        migrations.AddField(
            model_name='aboutmissionvision',
            name='vision_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='aboutmissionvision',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_mission_vision/'),
        ),
        migrations.AddField(
            model_name='aboutmissionvision',
            name='vision_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
