# Generated by Django 5.1.7 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_abouttailorguidance_aboutwhycrossroads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutwhycrossroadstitle',
            name='highlights',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
