# Generated by Django 5.1.7 on 2025-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_aboutwhycrossroadstitle_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOurValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_values/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutCoursesOfferedTitle',
            new_name='AboutOurValuesTitle',
        ),
        migrations.DeleteModel(
            name='AboutCoursesOffered',
        ),
    ]
