# Generated by Django 5.1.7 on 2025-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_aboutourvalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutwhycrossroadstitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_why_choose_us/'),
        ),
    ]
