# Generated by Django 5.1.7 on 2025-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_bannerblog_blogposts_delete_blogbanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='dedicated_page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
