# Generated by Django 5.1.7 on 2025-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogposts_dedicated_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='dedicated_page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
