# Generated by Django 5.1.7 on 2025-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerycreate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycreate',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
