# Generated by Django 5.1.7 on 2025-04-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_countryservicebanner_courseservicebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationAssistanceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationAssistanceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='services.documentationassistancetab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
