# Generated by Django 5.1.7 on 2025-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_documentationassistancetab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationassistancelisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documentation_assistance_listing/'),
        ),
    ]
