# Generated by Django 5.1.7 on 2025-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_languagelablisting_main_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryservicebanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courseservicebanner',
            name='description',
        ),
    ]
