# Generated by Django 5.1.7 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_countryservicebanner_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='country_service_banner/')),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
