# Generated by Django 5.1.7 on 2025-04-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryservicebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_service/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(blank=True, null=True, upload_to='country_service/'),
        ),
        migrations.CreateModel(
            name='DestinationDedicatedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='country_service/')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_button_name', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDedicatedKeyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_fact', to='services.destinationdedicatedpage')),
            ],
        ),
    ]
