# Generated by Django 5.1.7 on 2025-05-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_destinationdedicatedkeyfact_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDedicatedChooseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(blank=True, max_length=255, null=True)),
                ('list_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chooes_list', to='services.destinationdedicatedpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDedicatedChooseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_title', to='services.destinationdedicatedpage')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDedicatedIntakeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_information', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_information', to='services.destinationdedicatedpage')),
            ],
        ),
    ]
