# Generated by Django 5.1.7 on 2025-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_destinationdedicatedchooselist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationdedicatedchoosetitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choose_background/'),
        ),
    ]
