# Generated by Django 5.1.7 on 2025-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_destinationdedicatedchoosetitle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationdedicatedintakeinformation',
            name='intake_information_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
