# Generated by Django 5.1.7 on 2025-05-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_destinationdedicatedintakeinformation_intake_information_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationdedicatedchooselist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='destinationdedicatedchoosetitle',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='destinationdedicatedintakeinformation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='destinationdedicatedkeyfact',
            name='slug',
        ),
    ]
