# Generated by Django 5.1.7 on 2025-05-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_destinationdedicatedchooselist_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationdedicatedpage',
            name='slug',
        ),
    ]
