# Generated by Django 5.1.7 on 2025-05-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_destinationdedicatedpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdedicatedchooselist',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_list', to='services.destinationdedicatedpage'),
        ),
    ]
