# Generated by Django 5.1.7 on 2025-05-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_destinationdedicatedchooselist_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDedicatedAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_assistance', to='services.destinationdedicatedpage')),
            ],
        ),
    ]
