# Generated by Django 5.1.7 on 2025-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
