# Generated by Django 5.1.7 on 2025-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_banner/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
