# Generated by Django 5.1.7 on 2025-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_infohub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohub',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
