# Generated by Django 5.1.7 on 2025-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_infohub_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohub',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
