# Generated by Django 5.1.7 on 2025-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_infohub_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohub',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infohub',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
