# Generated by Django 5.1.7 on 2025-04-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourses',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='popularcourses',
            name='title',
        ),
    ]
