# Generated by Django 5.1.7 on 2025-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_popularcourses_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonial_videos/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.ImageField(upload_to='flags/')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
