# Generated by Django 5.1.7 on 2025-04-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_testimonialimage_testimonialvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialImage',
        ),
        migrations.DeleteModel(
            name='TestimonialVideo',
        ),
    ]
