# Generated by Django 5.1.7 on 2025-05-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_freeeducationcourses_freecoursedetailpagebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursedetailpagebanner',
            name='course_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='courses.courselisting'),
        ),
        migrations.AlterField(
            model_name='courselisting',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freecoursedetailpagebanner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='courses.freeeducationcourses'),
        ),
        migrations.AlterField(
            model_name='freeeducationcourses',
            name='link',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
