# Generated by Django 5.1.7 on 2025-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_freecoursedetailpagebanner_course_listing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselisting',
            options={'ordering': ['order'], 'verbose_name': 'Course Listing', 'verbose_name_plural': 'Course Listings'},
        ),
        migrations.AlterModelOptions(
            name='freecoursedetailpagebanner',
            options={'verbose_name': 'Free Course Detail Page Banner', 'verbose_name_plural': 'Free Course Detail Page Banners'},
        ),
        migrations.AlterModelOptions(
            name='freeeducationcourses',
            options={'ordering': ['order'], 'verbose_name': 'Free Education Course', 'verbose_name_plural': 'Free Education Courses'},
        ),
        migrations.AlterModelOptions(
            name='popularcourses',
            options={'ordering': ['order'], 'verbose_name': 'Popular Course', 'verbose_name_plural': 'Popular Courses'},
        ),
        migrations.AddIndex(
            model_name='courselisting',
            index=models.Index(fields=['link'], name='courses_cou_link_dd4e92_idx'),
        ),
        migrations.AddIndex(
            model_name='freeeducationcourses',
            index=models.Index(fields=['link'], name='courses_fre_link_5f8286_idx'),
        ),
    ]
