# Generated by Django 5.1.7 on 2025-05-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courselisting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecoursedetailpagebanner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='courses.freeeducationcourses'),
        ),
        migrations.AlterField(
            model_name='freecoursedetailpagebanner',
            name='course_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='courses.courselisting'),
        ),
        migrations.CreateModel(
            name='FreeCourseDetailPageTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='courses.freeeducationcourses')),
                ('course_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='courses.courselisting')),
            ],
            options={
                'verbose_name': 'Free Course Detail Page Tab',
                'verbose_name_plural': 'Free Course Detail Page Tabs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FreeCourseDetailPageTabContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='course_tab_images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.freecoursedetailpagetab')),
            ],
            options={
                'verbose_name': 'Free Course Detail Page Tab Content',
                'verbose_name_plural': 'Free Course Detail Page Tab Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FreeCourseDetailPageWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='courses.freeeducationcourses')),
                ('course_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='courses.courselisting')),
            ],
            options={
                'verbose_name': 'Free Course Detail Page Why Choose Item',
                'verbose_name_plural': 'Free Course Detail Page Why Choose Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FreeCourseDetailPageWhyChooseTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_titles', to='courses.freeeducationcourses')),
                ('course_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_titles', to='courses.courselisting')),
            ],
            options={
                'verbose_name': 'Free Course Detail Page Why Choose Title',
                'verbose_name_plural': 'Free Course Detail Page Why Choose Titles',
            },
        ),
    ]
