# Generated by Django 5.1.7 on 2025-05-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_freecoursedetailpagebanner_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecoursedetailpagebanner',
            options={'ordering': ['order'], 'verbose_name': 'Free Course Detail Page Banner', 'verbose_name_plural': 'Free Course Detail Page Banners'},
        ),
        migrations.AddField(
            model_name='freecoursedetailpagebanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freecoursedetailpagebanner',
            name='banner_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
