# Generated by Django 5.1.7 on 2025-05-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_freecoursedetailpagebanner_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursedetailpagewhychoosetitle',
            name='course',
        ),
    ]
