# Generated by Django 5.1.7 on 2025-05-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_freecoursedetailpagewhychoosetitle_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursedetailpagebanner',
            name='course',
        ),
        migrations.RemoveField(
            model_name='freecoursedetailpagetab',
            name='course',
        ),
        migrations.RemoveField(
            model_name='freecoursedetailpagewhychoose',
            name='course',
        ),
        migrations.RemoveField(
            model_name='freecoursedetailpagewhychoosetitle',
            name='course',
        ),
    ]
