# Generated by Django 5.1.7 on 2025-04-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_banner/')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
