# Generated by Django 5.1.7 on 2025-04-19 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialTabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonial_stories_videos/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('testimonials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_listings', to='testimonials.testimonialtabs')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_stories_images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('testimonials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_listings', to='testimonials.testimonialtabs')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
