# Generated by Django 5.1.7 on 2025-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonialtabs_testimoniallistingvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoniallistingimage',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimoniallistingvideo',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
