# Generated by Django 5.1.7 on 2025-05-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0002_newseventstab_newseventslisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseventslisting',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newseventslisting',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
