# Generated by Django 5.1.7 on 2025-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0004_alter_newseventslisting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseventslisting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
