# Generated by Django 5.1.7 on 2025-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0006_remove_newseventslisting_news_events_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newseventslisting',
            name='title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
