# Generated by Django 5.1.7 on 2025-05-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0007_alter_newseventslisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_event_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_event_location',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/'),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_time',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='detailed_page_title',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
