# Generated by Django 5.1.7 on 2025-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0008_newseventslisting_detailed_page_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseventslisting',
            name='google_map_latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newseventslisting',
            name='google_map_longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
