# Generated by Django 5.1.7 on 2025-05-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0009_newseventslisting_google_map_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEventsRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events_recap_images/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='news_and_events.newseventslisting')),
            ],
        ),
    ]
