# Generated by Django 5.1.7 on 2025-05-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_education', '0002_freeeducationdedicatedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeeducationcountry',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to='free_education_country/'),
        ),
        migrations.CreateModel(
            name='FreeEducationCountryDedicatedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='free_education_country/')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('free_education_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_education_country', to='free_education.freeeducationcountry')),
            ],
        ),
        migrations.DeleteModel(
            name='FreeEducationDedicatedPage',
        ),
    ]
