# Generated by Django 5.1.7 on 2025-05-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_education', '0003_alter_freeeducationcountry_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeeducationcountrydedicatedpage',
            name='free_education_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_pages', to='free_education.freeeducationcountry'),
        ),
    ]
