# Generated by Django 5.1.7 on 2025-05-10 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_education', '0005_freeeducationcountrydedicatedpagekeyfactlisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeEducationCountryDedicatedPageRequirementsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(blank=True, max_length=255, null=True)),
                ('list_description', models.TextField(blank=True, null=True)),
                ('free_education_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_listings', to='free_education.freeeducationcountry')),
            ],
        ),
        migrations.CreateModel(
            name='FreeEducationCountryDedicatedPageRequirementsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_background_image', models.ImageField(blank=True, null=True, upload_to='free_education_country/')),
                ('requirement_title', models.CharField(blank=True, max_length=255, null=True)),
                ('requirement_description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('free_education_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_titles', to='free_education.freeeducationcountry')),
            ],
        ),
    ]
