# Generated by Django 5.1.7 on 2025-04-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_freeeducationcourses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeeducationcourses',
            old_name='link_text',
            new_name='link',
        ),
    ]
