# Generated by Django 5.1.7 on 2025-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEventsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='freeeducationtitle',
            options={},
        ),
        migrations.RemoveField(
            model_name='freeeducationtitle',
            name='order',
        ),
    ]
