# Generated by Django 5.1.7 on 2025-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_testimonialimage_testimonialvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_images/'),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialimage',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialvideo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialvideo',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialvideo',
            name='video',
            field=models.FileField(upload_to='testimonial_videos/'),
        ),
    ]
