# Generated by Django 5.1.7 on 2025-04-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homebanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='testimonial_videos/'),
        ),
    ]
