# Generated by Django 5.1.7 on 2025-05-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_testimonialvideo_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsEvents',
        ),
    ]
