# Generated by Django 5.1.7 on 2025-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_newsevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeeducationcountry',
            name='link',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
