# Generated by Django 5.1.7 on 2025-05-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_freeeducationcountry_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeEducationCountry',
        ),
        migrations.DeleteModel(
            name='FreeEducationTitle',
        ),
    ]
