# Generated by Django 5.1.7 on 2025-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_freeeducationcountry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeEducationCourses',
        ),
    ]
