# Generated by Django 5.1.7 on 2025-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_freeeducationcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='contact_us_url',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
