# Generated by Django 5.1.7 on 2025-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homebanner_contact_us_url_homebanner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='button_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
